
#ifndef _DEFS__H
#define _DEFS__H

#include <SDL_rect.h>

const int SCREEN_WIDTH = 800;

const int SCREEN_HEIGHT = 600;
const char* WINDOW_TITLE = "Boboiboy";

#define BACKGROUND_IMG "img\\forest.jpg"

const int PLAYER_MOVE_SPEED   = 6;
const float PLAYER_JUMP_FORCE = -9.0f;
const float PLAYER_GRAVITY    = 0.35f;
const int SWIM_SPEED = 6;

const float PLAYER_DEATH_BOUNCE_VY = -7.0f;
const int PLAYER_DEATH_BOUNCE_DX = 3;

const char* PLAYER_STAND_FILE = "bg\\boboiboy_stand.png";
const char* MAN_SPRITE_FILE = "bg\\boboiboy_run.png";
const char* MAN_SWIM_FILE = "bg\\boboiboy_swim.png";

const int BOBOIBOY_FRAME_WIDTH  = 125;
const int BOBOIBOY_FRAME_HEIGHT = 167;

const int MAN_CLIPS[][4] = {
    { 0 * BOBOIBOY_FRAME_WIDTH, 0 * BOBOIBOY_FRAME_HEIGHT, BOBOIBOY_FRAME_WIDTH, BOBOIBOY_FRAME_HEIGHT },
    { 1 * BOBOIBOY_FRAME_WIDTH, 0 * BOBOIBOY_FRAME_HEIGHT, BOBOIBOY_FRAME_WIDTH, BOBOIBOY_FRAME_HEIGHT },
    { 2 * BOBOIBOY_FRAME_WIDTH, 0 * BOBOIBOY_FRAME_HEIGHT, BOBOIBOY_FRAME_WIDTH, BOBOIBOY_FRAME_HEIGHT },
    { 3 * BOBOIBOY_FRAME_WIDTH, 0 * BOBOIBOY_FRAME_HEIGHT, BOBOIBOY_FRAME_WIDTH, BOBOIBOY_FRAME_HEIGHT },
    { 0 * BOBOIBOY_FRAME_WIDTH, 1 * BOBOIBOY_FRAME_HEIGHT, BOBOIBOY_FRAME_WIDTH, BOBOIBOY_FRAME_HEIGHT },
    { 1 * BOBOIBOY_FRAME_WIDTH, 1 * BOBOIBOY_FRAME_HEIGHT, BOBOIBOY_FRAME_WIDTH, BOBOIBOY_FRAME_HEIGHT },
    { 2 * BOBOIBOY_FRAME_WIDTH, 1 * BOBOIBOY_FRAME_HEIGHT, BOBOIBOY_FRAME_WIDTH, BOBOIBOY_FRAME_HEIGHT },
    { 3 * BOBOIBOY_FRAME_WIDTH, 1 * BOBOIBOY_FRAME_HEIGHT, BOBOIBOY_FRAME_WIDTH, BOBOIBOY_FRAME_HEIGHT },
    { 0 * BOBOIBOY_FRAME_WIDTH, 2 * BOBOIBOY_FRAME_HEIGHT, BOBOIBOY_FRAME_WIDTH, BOBOIBOY_FRAME_HEIGHT },
    { 1 * BOBOIBOY_FRAME_WIDTH, 2 * BOBOIBOY_FRAME_HEIGHT, BOBOIBOY_FRAME_WIDTH, BOBOIBOY_FRAME_HEIGHT },
    { 2 * BOBOIBOY_FRAME_WIDTH, 2 * BOBOIBOY_FRAME_HEIGHT, BOBOIBOY_FRAME_WIDTH, BOBOIBOY_FRAME_HEIGHT },
    { 3 * BOBOIBOY_FRAME_WIDTH, 2 * BOBOIBOY_FRAME_HEIGHT, BOBOIBOY_FRAME_WIDTH, BOBOIBOY_FRAME_HEIGHT }
};

const int MAN_FRAMES = sizeof(MAN_CLIPS) / sizeof(MAN_CLIPS[0]); // Sẽ tính ra 12


const int SWIM_FRAME_WIDTH  = 153;
const int SWIM_FRAME_HEIGHT = 136;

const int MAN_SWIM[][4] = {
    { 0 * SWIM_FRAME_WIDTH, 0 * SWIM_FRAME_HEIGHT, SWIM_FRAME_WIDTH, SWIM_FRAME_HEIGHT },
    { 1 * SWIM_FRAME_WIDTH, 0 * SWIM_FRAME_HEIGHT, SWIM_FRAME_WIDTH, SWIM_FRAME_HEIGHT },
    { 2 * SWIM_FRAME_WIDTH, 0 * SWIM_FRAME_HEIGHT, SWIM_FRAME_WIDTH, SWIM_FRAME_HEIGHT },
    { 3 * SWIM_FRAME_WIDTH, 0 * SWIM_FRAME_HEIGHT, SWIM_FRAME_WIDTH, SWIM_FRAME_HEIGHT },
    { 0 * SWIM_FRAME_WIDTH, 1 * SWIM_FRAME_HEIGHT, SWIM_FRAME_WIDTH, SWIM_FRAME_HEIGHT },
    { 1 * SWIM_FRAME_WIDTH, 1 * SWIM_FRAME_HEIGHT, SWIM_FRAME_WIDTH, SWIM_FRAME_HEIGHT },
    { 2 * SWIM_FRAME_WIDTH, 1 * SWIM_FRAME_HEIGHT, SWIM_FRAME_WIDTH, SWIM_FRAME_HEIGHT },
    { 3 * SWIM_FRAME_WIDTH, 1 * SWIM_FRAME_HEIGHT, SWIM_FRAME_WIDTH, SWIM_FRAME_HEIGHT },
    { 0 * SWIM_FRAME_WIDTH, 2 * SWIM_FRAME_HEIGHT, SWIM_FRAME_WIDTH, SWIM_FRAME_HEIGHT },
    { 1 * SWIM_FRAME_WIDTH, 2 * SWIM_FRAME_HEIGHT, SWIM_FRAME_WIDTH, SWIM_FRAME_HEIGHT },
    { 2 * SWIM_FRAME_WIDTH, 2 * SWIM_FRAME_HEIGHT, SWIM_FRAME_WIDTH, SWIM_FRAME_HEIGHT },
    { 3 * SWIM_FRAME_WIDTH, 2 * SWIM_FRAME_HEIGHT, SWIM_FRAME_WIDTH, SWIM_FRAME_HEIGHT }
};

const int SWIM_FRAMES = sizeof(MAN_SWIM) / sizeof(MAN_SWIM[0]); // Sẽ tính ra 12

const char* HEART_ICON = "img\\heart_icon.png";
const int HEART_ICON_WIDTH = 32;
const int HEART_ICON_HEIGHT = 32;

const char* NOTI_5_LIFE = "img\\5_LIFE.png";
const char* NOTI_4_LIFE = "img\\4_LIFE.png";
const char* NOTI_3_LIFE = "img\\3_LIFE.png";
const char* NOTI_2_LIFE = "img\\2_LIFE.png";
const char* NOTI_1_LIFE = "img\\1_LIFE.png";
const char* NOTI_0_LIFE = "img\\0_LIFE.png";

const char* SETTING_BUTTON_FILE="img\\setting_button.png";
const SDL_Rect SETTING_BUTTON_RECT={666,23,73,73};

enum class StageOutcome {
    COMPLETED,
    PLAYER_DIED,
    GO_TO_MENU,
    QUIT_APPLICATION
};

// Các trạng thái có thể có bên trong một màn chơi (cho Pause/Settings)
enum class StageState {
    PLAYING,
    PAUSED_SETTINGS
};

enum class AppState {
    MENU,
    STAGE_1,
    STAGE_2,
    STAGE_3,
    GAME_OVER,
    GAME_WON,
    QUITTING
};

enum class MenuResult {
    START_GAME,
    QUIT_APPLICATION
};

#endif

